"""create migrations

Revision ID: d1e603d2dba1
Revises: 1326dd7a36ba
Create Date: 2023-09-25 00:36:44.326332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1e603d2dba1'
down_revision = '1326dd7a36ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('dept', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('dept')
        batch_op.drop_column('task')

    # ### end Alembic commands ###
